# Generated by Django 4.0.4 on 2022-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=100)),
                ('bidderId', models.CharField(max_length=100)),
                ('bidAmount', models.IntegerField()),
            ],
        ),
    ]
