# Generated by Django 4.0.4 on 2022-04-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_defects',
            new_name='product_details',
        ),
    ]
